# Generated by Django 5.1.3 on 2025-01-03 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='phoneNumber',
            new_name='age',
        ),
    ]
